name: Publish npm packages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install pnpm
        run: npm i pnpm@8 -g
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: install dependencies
        run: pnpm install
      - name: Publish with Lerna
        env:
          GH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name lexmin0412
          git config user.email zhangle_dev@outlook.com
          pnpm ci:version
          pnpm ci:publish
