name: Publish npm packages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: pnpm/action-setup@v2 # pnpm is optional but recommended, you can also use npm / yarn
        with:
          version: 8
          cache: pnpm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Publish with Lerna
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          git config user.name lexmin0412
          git config user.email zhangle_dev@outlook.com
          lerna publish from-package --yes --otp ${{secrets.npm_token}}
